"""A structured summary of a conversation for the owner to hand to their
vet (GET /conversations/{id}/summary).

Written by the model from the conversation and the pet's profile, inside
fixed sections, in Italian; wrapped in a deterministic header and footer
that say it was generated by the app's assistant and is not a diagnosis.
The text that leaves for the provider is anonymized like every other
prompt; the owner's own name is never part of the summary.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

from pydantic import BaseModel

from packages.core.application.ports.conversation_repository import ConversationRepository
from packages.core.application.ports.llm_client import LLMClient, LLMGenerationRequest
from packages.core.application.ports.pet_profile_repository import PetProfileRepository
from packages.core.application.ports.pii_anonymizer import PiiAnonymizationRequest, PiiAnonymizer
from packages.core.application.services.medical_record_context_retriever import italian_date
from packages.core.domain.conversation.models import Conversation
from packages.core.domain.pet_profile.models import PetProfile
from packages.shared.errors.base import ValidationError

VET_SUMMARY_MARKER = "a vet from a chat the owner had with the app's assistant"

SECTIONS = (
    "Animale",
    "Motivo del contatto",
    "Sintomi riferiti dal proprietario e quando",
    "Cosa è stato osservato",
    "Documenti citati",
    "Domande aperte per il veterinario",
)

# The fixed line the chat writes when it reads a record: lists the
# documents the conversation actually used.
_READ_LINE = re.compile(r"Ho letto (.+?)\.(?:\n|$)")
_DOCUMENT_LABEL = re.compile(r"«[^»]+» del [^«»]+?(?= e «|$)")


class VetSummaryInput(BaseModel):
    owner_id: str
    conversation_id: str
    owner_names: list[str] = []


class VetSummaryOutput(BaseModel):
    summary: str
    generated_at: datetime


class VetSummaryService:
    def __init__(
        self,
        repository: ConversationRepository,
        pet_profile_repository: PetProfileRepository,
        llm_client: LLMClient,
        pii_anonymizer: PiiAnonymizer,
    ) -> None:
        self._repository = repository
        self._pet_profile_repository = pet_profile_repository
        self._llm_client = llm_client
        self._pii_anonymizer = pii_anonymizer

    def execute(self, data: VetSummaryInput) -> VetSummaryOutput:
        """Raises ValidationError when the conversation is not the owner's
        or has no owner message yet, ProviderError when the model is
        unavailable."""
        conversation = self._repository.get(data.conversation_id)
        if conversation is None or conversation.owner_id != data.owner_id:
            raise ValidationError("conversation not found")
        if not any(message.role == "user" for message in conversation.messages):
            raise ValidationError("conversation_empty: la conversazione non ha ancora messaggi")
        pet = self._pet_profile_repository.get(conversation.pet_id)
        now = datetime.now(UTC)

        response = self._llm_client.generate(
            LLMGenerationRequest(
                system_prompt=self._system_prompt(),
                user_prompt=self._user_prompt(conversation, pet, data.owner_names),
                temperature=0.1,
                max_tokens=1200,
            )
        )
        body = response.content.strip()
        return VetSummaryOutput(
            summary=f"{self._header(pet, conversation, now)}\n\n{body}\n\n{self._footer()}",
            generated_at=now,
        )

    @staticmethod
    def _system_prompt() -> str:
        sections = "\n".join(f"## {section}" for section in SECTIONS)
        return (
            f"You are writing, in Italian, a short structured summary for {VET_SUMMARY_MARKER}. "
            "The reader is a veterinarian: factual, compact, clinical register is fine, no "
            "advice to the vet and no diagnosis of your own. Report ONLY what the conversation "
            "and the profile contain; never add a symptom, a value or an observation that is "
            "not there. Keep the owner's time references ('da ieri', 'da una settimana') and "
            "turn them into dates when the conversation dates allow it. Where the "
            "conversation says nothing for a section, write 'Non riferito'. Never mention the "
            "owner's name or any contact detail. Under 'Documenti citati' list only documents "
            "the conversation actually referred to. Under 'Domande aperte' list what the "
            "owner asked that remained open or that the assistant deferred to the vet.\n\n"
            "Use exactly these markdown sections, in this order, with short bullet points or "
            f"one or two sentences each:\n{sections}"
        )

    def _user_prompt(
        self, conversation: Conversation, pet: PetProfile | None, owner_names: list[str]
    ) -> str:
        lines = []
        if pet is not None:
            lines.append(
                "Pet profile: "
                + ", ".join(
                    part
                    for part in (
                        f"name {self._anonymize(pet.name, owner_names)}",
                        f"species {pet.species}",
                        f"breed {pet.breed}" if pet.breed else "",
                        f"age {pet.age_years} years" if pet.age_years is not None else "",
                        f"sex {pet.sex}" if pet.sex else "",
                        f"weight {pet.weight_label}" if pet.weight_label else "",
                        f"notes: {self._anonymize(pet.notes, owner_names)}" if pet.notes else "",
                    )
                    if part
                )
            )
        documents = self._documents_cited(conversation)
        if documents:
            lines.append(
                "Documents the assistant read during the conversation: " + "; ".join(documents)
            )
        lines.append("Conversation (oldest first):")
        for message in conversation.messages:
            when = message.created_at.date().isoformat()
            who = "Owner" if message.role == "user" else "Assistant"
            attached = " [a file was attached]" if message.attachment_id else ""
            lines.append(
                f"[{when}] {who}{attached}: {self._anonymize(message.content, owner_names)}"
            )
        return "\n".join(lines)

    @staticmethod
    def _documents_cited(conversation: Conversation) -> list[str]:
        found: list[str] = []
        for message in conversation.messages:
            if message.role != "assistant":
                continue
            for match in _READ_LINE.finditer(message.content):
                for label in _DOCUMENT_LABEL.findall(match.group(1)):
                    if label not in found:
                        found.append(label)
        return found

    def _anonymize(self, text: str, owner_names: list[str]) -> str:
        return self._pii_anonymizer.anonymize(
            PiiAnonymizationRequest(text=text, known_person_names=owner_names)
        ).anonymized_text

    @staticmethod
    def _header(pet: PetProfile | None, conversation: Conversation, now: datetime) -> str:
        first = next((m for m in conversation.messages if m.role == "user"), None)
        started = italian_date(first.created_at.date()) if first else italian_date(now.date())
        subject = f"{pet.name} ({pet.species})" if pet else "l'animale"
        return (
            f"# Riassunto per il veterinario — {subject}\n\n"
            f"Generato automaticamente dall'assistente dell'app il {italian_date(now.date())} "
            f"da una conversazione iniziata il {started}. Non è una diagnosi né un parere "
            "veterinario: riporta ciò che il proprietario ha scritto all'assistente."
        )

    @staticmethod
    def _footer() -> str:
        return (
            "---\n"
            "Testo generato da un assistente automatico sulla base di quanto riferito dal "
            "proprietario; da verificare con la visita. Nessun dato personale del "
            "proprietario è incluso."
        )
