from fastapi import APIRouter, Response

from apps.api.dependencies.container import get_container
from apps.api.schemas.conversations import RenameConversationRequest
from packages.core.application.services.delete_conversation import DeleteConversationInput
from packages.core.application.services.list_conversations import ListConversationsInput
from packages.core.application.services.rename_conversation import RenameConversationInput
from packages.core.application.services.send_chat_message import owner_names_for_anonymization
from packages.core.application.services.vet_summary import VetSummaryInput

router = APIRouter(prefix="/conversations", tags=["conversations"])


@router.get("")
def list_conversations() -> dict[str, object]:
    container = get_container()
    user = container.auth_provider.get_current_user()
    result = container.list_conversations_service().execute(
        ListConversationsInput(owner_id=user.id)
    )
    return result.model_dump()


@router.patch("/{conversation_id}")
def rename_conversation(
    conversation_id: str, request: RenameConversationRequest
) -> dict[str, object]:
    """The owner's own title for a conversation (validated and tidied)."""
    container = get_container()
    user = container.auth_provider.get_current_user()
    result = container.rename_conversation_service().execute(
        RenameConversationInput(
            owner_id=user.id, conversation_id=conversation_id, title=request.title
        )
    )
    return {"id": result.conversation.id, "title": result.conversation.title}


@router.get("/{conversation_id}/summary")
def conversation_summary(conversation_id: str) -> dict[str, object]:
    """A structured summary of the conversation to hand to the vet:
    generated by the assistant, not a diagnosis (it says so itself)."""
    container = get_container()
    user = container.auth_provider.get_current_user()
    conversation = container.conversation_repository.get(conversation_id)
    pet = container.pet_profile_repository.get(conversation.pet_id) if conversation else None
    result = container.vet_summary_service().execute(
        VetSummaryInput(
            owner_id=user.id,
            conversation_id=conversation_id,
            owner_names=owner_names_for_anonymization(
                user.display_name, pet_name=pet.name if pet else ""
            ),
        )
    )
    return {"summary": result.summary, "generated_at": result.generated_at.isoformat()}


@router.delete("/{conversation_id}", status_code=204)
def delete_conversation(conversation_id: str) -> Response:
    container = get_container()
    user = container.auth_provider.get_current_user()
    container.delete_conversation_service().execute(
        DeleteConversationInput(owner_id=user.id, conversation_id=conversation_id)
    )
    return Response(status_code=204)
