from enum import StrEnum


class ConversationState(StrEnum):
    """Explicit conversation outcomes (spec v3 §39) — replaces collapsing every
    outcome into a generic answer string."""

    NEED_MORE_INFORMATION = "NEED_MORE_INFORMATION"
    POSSIBLE_URGENT_CASE = "POSSIBLE_URGENT_CASE"
    ADEQUATE_EVIDENCE_FOUND = "ADEQUATE_EVIDENCE_FOUND"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    RETRIEVAL_FAILURE = "RETRIEVAL_FAILURE"
    SOURCE_VALIDATION_FAILURE = "SOURCE_VALIDATION_FAILURE"
    USER_DECLINED_RECORD_ACCESS = "USER_DECLINED_RECORD_ACCESS"
    USER_STOPPED_INTERVIEW = "USER_STOPPED_INTERVIEW"
