from typing import Protocol

from packages.core.domain.feedback.models import ChatResponseReport, ChatResponseReportCounter


class ChatResponseReportRepository(Protocol):
    def save(self, report: ChatResponseReport) -> ChatResponseReport: ...

    def get(self, report_id: str) -> ChatResponseReport | None: ...

    def list_by_reporter(self, reporter_ref: str) -> list[ChatResponseReport]: ...

    def list_all(self) -> list[ChatResponseReport]: ...

    def delete(self, report_id: str) -> None: ...

    def add_to_counter(self, period: str, reason: str, status: str, amount: int) -> None: ...

    def list_counters(self) -> list[ChatResponseReportCounter]: ...
